Add more skips
Motivated by a CRAN failure I came across while checking as the v1.6.0 results rolled in. CRAN has not said anything and I suspect it may go away? The root cause seems to be that the test system is acting like a read-only file system. Maybe they are testing with a non-writeable user home directory? In any case, I was looking at these tests and decided these skips were a good idea, in any case.

---

CRAN Package Check Results for Package usethis
Last updated on 2020-04-11 16:47:35 CEST.
Flavor: r-release-osx-x86_64

Version: 1.6.0
Check: tests
Result: ERROR
     Running ‘spelling.R’ [0s/0s]
     Running ‘testthat.R’ [38s/41s]
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
     ── 1. Error: git_config returns old global values (@test-git-utils.R#15) ──────
     failed to create locked file '/Users/urbanek/.gitconfig.lock': Read-only file system
     Backtrace:
     1. usethis:::git_config(usethis.test1 = "val1", usethis.test2 = "val2")

     ── 2. Failure: conspicuous_place() returns a writeable directory (@test-use-cour
     file_access(x, mode = "write") isn't true.

     ══ testthat results ═══════════════════════════════════════════════════════════
     [ OK: 477 | SKIPPED: 29 | WARNINGS: 0 | FAILED: 2 ]
     1. Error: git_config returns old global values (@test-git-utils.R#15)
     2. Failure: conspicuous_place() returns a writeable directory (@test-use-course.R#201)

     Error: testthat unit tests failed
     Execution halted